### PR TITLE
Add MTL instances

### PR DESCRIPTION
**Pull request by felixSchl**
Seems fair to add these even if things are bit in flux right now with the talk about moving away from Eff in purescript itself.

### CODE REVIEW

**Comment by jdegoes** [comment]
Thank you!

**Comment by felixSchl** [comment]
Any chance for a minor version bump for me to depend on downstream?

**Comment by jdegoes** [comment]
@felixSchl Yes, but first, there's an issue that needs fixing around `ParIO` instances. Should be pretty easy to fix than we can do a minor version bump.

**Comment by jdegoes** [comment]
@felixSchl Done!

**Comment by felixSchl** [comment]
Awesome, thank you :)

**Pull request merged**
